apiVersion: v1
kind: Pod
metadata:
  name: etcd
  namespace: kube-system
  labels:
    component: etcd
    tier: control-plane
spec:
  hostNetwork: true
  priorityClassName: system-node-critical
  containers:
    - name: etcd
      image: registry.k8s.io/etcd:3.5.12-0
      command:
        - etcd
        - --advertise-client-urls=http://127.0.0.1:2379
        - --listen-client-urls=http://0.0.0.0:2379
        - --data-dir=/var/lib/etcd
        - --listen-peer-urls=http://0.0.0.0:2380
        - --initial-cluster=default=http://127.0.0.1:2380
        - --initial-advertise-peer-urls=http://127.0.0.1:2380
        - --initial-cluster-state=new
        - --initial-cluster-token=etcd-cluster
      volumeMounts:
        - name: etcd-data
          mountPath: /var/lib/etcd
  volumes:
    - name: etcd-data
      hostPath:
        path: /var/lib/etcd
        type: DirectoryOrCreate