apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  namespace: kube-system
  labels:
    component: kube-controller-manager
    tier: control-plane
spec:
  hostNetwork: true
  priorityClassName: system-node-critical
  containers:
    - name: kube-controller-manager
      image: registry.k8s.io/kube-controller-manager:v1.30.0
      command:
        - kube-controller-manager
        - --kubeconfig=/etc/kubernetes/kubeconfig
        - --leader-elect=false
        - --cloud-provider=external
        - --service-cluster-ip-range=10.0.0.0/24
        - --cluster-name=kubernetes
        - --root-ca-file=/etc/kubernetes/pki/ca.crt
        - --service-account-private-key-file=/etc/kubernetes/pki/sa.key
        - --use-service-account-credentials=true
        - --v=2
        - --bind-address=0.0.0.0
      volumeMounts:
        - name: kubeconfig
          mountPath: /etc/kubernetes
          readOnly: true
        - name: pki
          mountPath: /etc/kubernetes/pki
          readOnly: true
  volumes:
    - name: kubeconfig
      hostPath:
        path: /var/lib/kubelet
        type: Directory
    - name: pki
      hostPath:
        path: /etc/kubernetes/pki
        type: Directory